---
- name: Linux Setup
  hosts: all
  connection: local
  become: true

  tasks:
    - name: Add vscode repository
      block:
        - name: Get key
          ansible.builtin.get_url:
            url: https://packages.microsoft.com/keys/microsoft.asc
            dest: /etc/apt/keyrings/microsoft.asc
            mode: "0664"

            # - name: Checksum
            #   ansible.builtin.command:
            #     cmd: gpg --dearmor < /tmp/microsoft.asc > /etc/apt/keyrings/packages.microsoft.gpg

        - name: Add repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/code stable main"
            state: present

    - name: Add github repository
      block:
        - name: Get key
          ansible.builtin.get_url:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
            mode: "0666"

        - name: Add repository
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
            state: present

    - name: Install apt packages
      ansible.builtin.package:
        update_cache: true
        upgrade: true
        state: latest
        name:
          - apt-transport-https
          - tmux
          - zsh
          - git
          - neovim
          - curl
          - wget
          - gpg
          - net-tools
          - unzip
          - jq
          - sshfs
          - code
          - python3
          - python3-pip
          - golang-go

    - name: Install pip packages
      ansible.builtin.pip:
        state: latest
        name:
          - virtualenv
          - pre-commit

    - name: Copy .zshrc file
      ansible.builtin.copy:
        src: files/zshrc
        dest: /home/jwtracy/.zshrc
        owner: jwtracy
        group: jwtracy
        mode: "0660"
#    - name: Add ansible user
#      ansible.builtin.user:
#        name: velociraptor
#        system: true
#
#    - name: Set up sudo for ansible user
#      ansible.builtin.copy:
#        src: files/sudoer_velociraptor
#        dest: /etc/sudoers.d/velociraptor
#        owner: root
#        group: root
#        mode: "0440"
#
#    - name: Add ansible-pull cron job
#      ansible.builtin.cron:
#        name: ansible auto-provision
#        user: velociraptor
#        minute: "*/10"
#        job: ansible-pull -o -U https://github.com/jwtracy/jwtsbots local.yaml
